### ISSUE TITLE
Apple Silicon macOS: vkCreateInstance: Found no drivers!

### ISSUE THREAD

**Issue by svenpeter42** [ngscopeclient/scopehal-docs#72]
When following the documentation for macOS it's (almost) possible to compile everything but some test running and the end and ngscopeclient itself refuse to run with ```ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!```.
This probably happens because vulkan has to go through MoltenVK to run on the Metal drivers available on macOS and these aren't loaded if only ```VULKAN_SDK``` and ```PATH``` are updated. I had to ```source setup-env.sh``` from ```~VulkanSDK/1.3.231.1/``` which also sets a few additional ```VK_``` variables to point towards MoltenVK. Everything works fine then. This should probably be added to the documentation.

**Comment by Johnsel** [comment]
You are right, and it should also be reflected in the CI script. Currently we have the documentation, CI script and reality all having different build 'instructions'. They should all be the same, working, process to build and run ngscopeclient.

@azonenberg I can't do it myself in this repo so please assign this ticket to me.

**Comment by d235j** [comment]
Should be fixed by #81 (which covers installation/loading of prerequisites and the SDK), and https://github.com/ngscopeclient/scopehal-apps/pull/673 (which ensures that `molten-vk` has been installed at build-time).

**Comment by azonenberg** [comment]
@Johnsel @d235j can we confirm this is fixed and close?

**Comment by azonenberg** [comment]
Believed to be fixed. @svenpeter42 please retest, if you confirm fixed or we don't hear anything from you in a week I'll close the issue.

**Comment by Johnsel** [comment]
> @Johnsel @d235j can we confirm this is fixed and close?

I'll defer to @d235j
